# Dobot — cook_vegetable
robot: dobot
default_prompt: "cook vegetable"

ckpt: /data/gxy/realworldRL/RLinf/logs/20260828-133705-hf_v21_dobot_sft_openpi_rlinf_pi05_cook_vegetable_hf_v21-gpu0/dobot_pi05_hf_v21_cook_vegetable_sft/checkpoints/global_step_30000/actor/model_state_dict
norm_stats: /data/gxy/realworldRL/checkpoints/assets/dobot_hf_v21/cook_vegetable/norm_stats.json

precision: bf16
host: 0.0.0.0
port: 8000

model:
  pi05: true
  num_action_chunks: 50
  action_dim: 14
  num_steps: 5
  add_value_head: false
  openpi:
    task: eval
    config_name: pi05_dobot
    num_images_in_input: 3
    discrete_state_input: true
    max_token_len: 200
    model_action_dim: 32
    paligemma_variant: gemma_2b
    action_expert_variant: gemma_300m
